require: rubocop-rails
inherit_gem:
  relaxed-rubocop: .rubocop.yml

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/BeginBlock:
  Enabled: false
Style/BlockComments:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table

# The following three cops are new, but pending being enabled by default
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
